name: code linter

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    code_linting:
        name: python code linting check
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install flake8
              run: |
                  python -m pip install flake8
            - name: Lint code
              run: |
                  flake8 airflow/travel_agency/dags/includes
